[env:esp32-s3-devkitm-1]

platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = espressif32

board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = d:\GitHub\airQualityMonitor_1\lib
lib_deps = 
	sh123/esp32_opus@^1.0.3
monitor_speed = 115200

; 指定为16MB的FLASH分区表
board_build.arduino.partitions = default_16MB.csv
; 指定FLASH和PSRAM的运行模式
board_build.arduino.memory_type = qio_opi
; 指定FLASH容量为16MB
board_upload.flash_size = 16MB
; 指定PSRAM容量为4MB
board_upload.psram_size = 8MB

build_flags = 
            -DBOARD_HAS_PSRAM
            -DCORE_DEBUG_LEVEL=4  # 启用详细日志
;            ; -DCONFIG_SPIRAM_MODE_OCT=1   ; 启用 Octal 模式
;            ; -DCONFIG_SPIRAM_SPEED_80M=1  ; 降频至 80MHz 确保稳定[3,6,10](@ref)
;            ; -DCONFIG_SPIRAM_MEMTEST_ENABLE=n
;            -DCONFIG_SPIRAM_MODE_QUAD=1  ; 替换为四线模式



