[env:esp32-s3-devkitm-1]

lib_extra_dirs = d:\GitHub\airQualityMonitor_1\lib
platform = espressif32
board = esp32-s3-devkitm-1
board_build.mcu = esp32s3
framework = arduino
; board_build.partitions = min_spiffs.csv
; board_build.filesystem = spiffs

; board_build.spiffs_size = 1MB         ; 分配1MB空间
; board_build.spiffs_start = 0x180000   ; 分区起始地址